name: Deneme
on:
  push:
    branches: [ main ]
    schedule: 
    - cron: "*/5 * * * *"

jobs:
  run_tests:
    name: sh dosya calistirma
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run script file
      run: sh ./test.sh