name: Deneme
on:
  push:
    branches: [ main ] 

jobs:
  run_tests:
    name: sh dosya calistirma
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run script file
      run: sh
